
const db=window.sgSupabase,$=s=>document.querySelector(s);let user=null,categories=[],products=[],orders=[],editing=null;
function msg(text,type=''){ $('#status').textContent=text;$('#status').className='msg '+type }
function slugify(s){return String(s||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now().toString().slice(-5)}
async function checkSession(){const {data:{session}}=await db.auth.getSession();if(!session)return showLogin();user=session.user;const {data,error}=await db.from('admin_users').select('role').eq('user_id',user.id).maybeSingle();if(error||!data||data.role!=='admin'){await db.auth.signOut();$('#loginMsg').textContent='This account is not authorized as an administrator.';return showLogin()}showDashboard();await loadAll()}
function showLogin(){$('#login').hidden=false;$('#dashboard').hidden=true;$('aside').style.display='none'}
function showDashboard(){$('#login').hidden=true;$('#dashboard').hidden=false;$('aside').style.display='flex'}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginMsg').textContent='Signing in…';const {data,error}=await db.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});if(error){$('#loginMsg').textContent=error.message;return}user=data.user;await checkSession()};
$('#signOut').onclick=async()=>{await db.auth.signOut();location.reload()};
async function loadAll(){msg('Loading store data…');const [c,p]=await Promise.all([db.from('categories').select('*').order('sort_order'),db.from('products').select('*,categories(name),product_variants(*)').order('created_at',{ascending:false})]);if(c.error||p.error){msg((c.error||p.error).message,'error');return}categories=c.data||[];products=p.data||[];$('#category').innerHTML=categories.map(c=>`<option value="${c.id}">${c.name}</option>`).join('');render();msg('Store connected. Changes here update the live product database.','success')}
function render(filter=''){let list=products.filter(p=>!filter||p.name.toLowerCase().includes(filter.toLowerCase())||(p.sku||'').toLowerCase().includes(filter.toLowerCase()));$('#statProducts').textContent=products.length;$('#statActive').textContent=products.filter(p=>p.is_active).length;$('#statStock').textContent=products.reduce((a,p)=>a+Number(p.stock_quantity||0),0);$('#statOne').textContent=products.filter(p=>p.is_one_of_one).length;$('#productTable').innerHTML=`<div class="row head"><span></span><span>Product</span><span>Category</span><span>Price</span><span>Stock</span><span>Status</span><span></span></div>`+list.map(p=>`<div class="row"><div class="thumb" style="background-image:url('${p.primary_image_url||''}')"></div><div><b>${p.name}</b><br><small>${p.sku||''}</small></div><span>${p.categories?.name||'—'}</span><span>₹${Number(p.price_inr||0).toLocaleString('en-IN')}</span><span>${p.stock_quantity}</span><span class="pill">${p.is_active?'Active':'Hidden'}</span><button class="editBtn" data-edit="${p.id}">Edit</button></div>`).join('');document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(products.find(p=>p.id===b.dataset.edit)))}

async function loadOrders(){
  msg('Loading orders…');
  const {data,error}=await db.from('orders').select('*,order_items(*)').order('created_at',{ascending:false});
  if(error){msg(error.message,'error');return}
  orders=data||[];renderOrders();msg('Orders loaded.','success');
}
function renderOrders(){
  const fmt=n=>'₹'+Number(n||0).toLocaleString('en-IN'),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  $('#orderTable').innerHTML=orders.length?orders.map(o=>{let a=o.shipping_address||{};return `<div class="orderCard"><div class="orderTop"><div><b>${esc(o.order_number)}</b><br><small>${new Date(o.created_at).toLocaleString('en-IN')}</small></div><b>${fmt(o.total_inr)}</b></div><div class="orderMeta"><div><small>CUSTOMER</small><br>${esc(o.customer_name)}<br>${esc(o.phone)}<br>${esc(o.email||'')}</div><div><small>DELIVERY</small><br>${esc(a.line1||'')} ${esc(a.line2||'')}<br>${esc(a.city||'')}, ${esc(a.state||'')} ${esc(a.pincode||'')}</div><div><small>PAYMENT</small><br>${esc(o.payment_status)}</div><div><small>ORDER STATUS</small><br>${esc(o.order_status)}</div></div><div class="orderItems">${(o.order_items||[]).map(i=>`<div class="orderItem"><span>${esc(i.product_name)} ${i.variant_label?'— '+esc(i.variant_label):''} × ${i.quantity}</span><b>${fmt(i.line_total_inr)}</b></div>`).join('')}</div><div class="orderActions"><select data-order-status="${o.id}"><option value="pending" ${o.order_status==='pending'?'selected':''}>Pending</option><option value="confirmed" ${o.order_status==='confirmed'?'selected':''}>Confirmed</option><option value="packed" ${o.order_status==='packed'?'selected':''}>Packed</option><option value="shipped" ${o.order_status==='shipped'?'selected':''}>Shipped</option><option value="delivered" ${o.order_status==='delivered'?'selected':''}>Delivered</option><option value="cancelled" ${o.order_status==='cancelled'?'selected':''}>Cancelled</option></select><select data-payment-status="${o.id}"><option value="pending" ${o.payment_status==='pending'?'selected':''}>Payment Pending</option><option value="paid" ${o.payment_status==='paid'?'selected':''}>Paid</option><option value="failed" ${o.payment_status==='failed'?'selected':''}>Failed</option><option value="refunded" ${o.payment_status==='refunded'?'selected':''}>Refunded</option></select><button data-save-order="${o.id}">Save Status</button></div></div>`}).join(''):'<p>No orders yet.</p>';
  document.querySelectorAll('[data-save-order]').forEach(b=>b.onclick=async()=>{let id=b.dataset.saveOrder,os=document.querySelector(`[data-order-status="${id}"]`).value,ps=document.querySelector(`[data-payment-status="${id}"]`).value;const {error}=await db.from('orders').update({order_status:os,payment_status:ps}).eq('id',id);if(error)return msg(error.message,'error');await loadOrders()});
}
function switchView(view){
  document.querySelectorAll('aside [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
  $('#productPanel').hidden=view==='orders';$('#orderPanel').hidden=view!=='orders';
  if(view==='orders')loadOrders();
}
document.querySelectorAll('aside [data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view==='orders'?'orders':'products'));
$('#refreshOrders').onclick=loadOrders;

$('#adminSearch').oninput=e=>render(e.target.value);$('#newProduct').onclick=()=>openEditor(null);$('#closeEditor').onclick=()=>$('#editor').hidden=true;
function openEditor(p){editing=p||null;$('#editor').hidden=false;$('#editorTitle').textContent=p?'Edit Product':'Add Product';$('#productId').value=p?.id||'';$('#name').value=p?.name||'';$('#category').value=p?.category_id||categories[0]?.id||'';$('#price').value=p?.price_inr||'';$('#oldPrice').value=p?.compare_at_price_inr||'';$('#sku').value=p?.sku||'';$('#stock').value=p?.stock_quantity??1;$('#badge').value=p?.badge||'';$('#material').value=p?.material||'';$('#weight').value=p?.weight_grams||'';$('#gemstone').value=p?.gemstone_name||'';$('#naturalLab').value=p?.natural_lab_status||'';$('#certification').value=p?.certification||'';$('#origin').value=p?.origin||'';$('#treatment').value=p?.treatment||'';$('#shape').value=p?.shape||'';$('#color').value=p?.color||'';$('#shortDesc').value=p?.short_description||'';$('#desc').value=p?.description||'';$('#active').checked=p?.is_active??true;$('#featured').checked=!!p?.is_featured;$('#oneOfOne').checked=!!p?.is_one_of_one;$('#imageUrl').value=p?.primary_image_url||'';$('#imagePreview').src=p?.primary_image_url||'';$('#deleteProduct').hidden=!p;$('#variantEditor').hidden=!p;if(p)renderVariants(p.product_variants||[])}
$('#imageFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;msg('Uploading image…');const safe=f.name.replace(/[^a-zA-Z0-9._-]/g,'-');const path=`${user.id}/${Date.now()}-${safe}`;const {error}=await db.storage.from('product-images').upload(path,f,{upsert:false});if(error){msg(error.message,'error');return}const {data}=db.storage.from('product-images').getPublicUrl(path);$('#imageUrl').value=data.publicUrl;$('#imagePreview').src=data.publicUrl;msg('Image uploaded. Save the product to use it.','success')};
$('#productForm').onsubmit=async e=>{e.preventDefault();let payload={category_id:$('#category').value,name:$('#name').value.trim(),short_description:$('#shortDesc').value.trim()||null,description:$('#desc').value.trim()||null,price_inr:Number($('#price').value),compare_at_price_inr:$('#oldPrice').value?Number($('#oldPrice').value):null,sku:$('#sku').value.trim()||null,material:$('#material').value.trim()||null,gemstone_name:$('#gemstone').value.trim()||null,natural_lab_status:$('#naturalLab').value.trim()||null,certification:$('#certification').value.trim()||null,origin:$('#origin').value.trim()||null,treatment:$('#treatment').value.trim()||null,shape:$('#shape').value.trim()||null,color:$('#color').value.trim()||null,weight_grams:$('#weight').value?Number($('#weight').value):null,is_one_of_one:$('#oneOfOne').checked,stock_quantity:Number($('#stock').value||0),is_active:$('#active').checked,is_featured:$('#featured').checked,badge:$('#badge').value.trim()||null,primary_image_url:$('#imageUrl').value.trim()||null};let res;if(editing){res=await db.from('products').update(payload).eq('id',editing.id).select('id').single()}else{payload.slug=slugify(payload.name);res=await db.from('products').insert(payload).select('id').single()}if(res.error){msg(res.error.message,'error');return}msg('Product saved successfully.','success');await loadAll();let saved=products.find(x=>x.id===res.data.id);openEditor(saved)};
$('#deleteProduct').onclick=async()=>{if(!editing||!confirm('Delete this product? This cannot be undone.'))return;const {error}=await db.from('products').delete().eq('id',editing.id);if(error){msg(error.message,'error');return}$('#editor').hidden=true;msg('Product deleted.','success');await loadAll()};
function renderVariants(list){$('#variantList').innerHTML=list.sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)).map(v=>`<div class="variantItem"><b>${v.label}</b><span>${v.carat??'—'} ct</span><span>${v.ratti??'—'} ratti</span><span>₹${Number(v.price_inr||0).toLocaleString('en-IN')}</span><span>${v.stock_quantity} stock</span><button data-delv="${v.id}">Delete</button></div>`).join('')||'<p>No carat/ratti options yet.</p>';document.querySelectorAll('[data-delv]').forEach(b=>b.onclick=async()=>{const {error}=await db.from('product_variants').delete().eq('id',b.dataset.delv);if(error)return msg(error.message,'error');await loadAll();editing=products.find(p=>p.id===editing.id);renderVariants(editing.product_variants||[])})}
$('#variantForm').onsubmit=async e=>{e.preventDefault();if(!editing)return;const payload={product_id:editing.id,label:$('#vLabel').value.trim(),carat:$('#vCarat').value?Number($('#vCarat').value):null,ratti:$('#vRatti').value?Number($('#vRatti').value):null,price_inr:$('#vPrice').value?Number($('#vPrice').value):Number(editing.price_inr),stock_quantity:Number($('#vStock').value||0),is_active:true};const {error}=await db.from('product_variants').insert(payload);if(error){msg(error.message,'error');return}e.target.reset();$('#vStock').value=1;await loadAll();editing=products.find(p=>p.id===editing.id);renderVariants(editing.product_variants||[]);msg('Carat/ratti option added.','success')};
checkSession();
