const $=s=>document.querySelector(s),money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
let products=[],cart=[],subtotal=0,discount=0,appliedPromo='';
const uuidRe=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function readCart(){try{const raw=JSON.parse(localStorage.getItem('sg_cart')||'[]');if(!Array.isArray(raw))return[];const normalized=raw.map(v=>typeof v==='string'?{productId:v,variantId:null,qty:1}:v);const cleaned=normalized.filter(i=>uuidRe.test(String(i?.productId||i?.product_id||'')));if(cleaned.length!==normalized.length)localStorage.setItem('sg_cart',JSON.stringify(cleaned));return cleaned}catch{return[]}}
function resolve(i){const p=products.find(x=>x.id===(i.productId||i.product_id));if(!p)return null;const v=(i.variantId||i.variant_id)?p.variants?.find(x=>x.id===(i.variantId||i.variant_id)):null;return {p,v,qty:Math.max(1,Number(i.qty||i.quantity||1)),price:Number(v?.price_inr||p.price||0)}}
function refreshTotals(){const total=Math.max(0,subtotal-discount);$('#checkoutSubtotal').textContent=money(subtotal);$('#checkoutTotal').textContent=money(total);$('#checkoutDiscount').textContent='− '+money(discount);$('#discountRow').style.display=discount>0?'flex':'none'}
async function applyPromo(){const input=$('#promoCode'),msg=$('#promoMsg'),btn=$('#applyPromo'),code=input.value.trim().toUpperCase();if(!code){appliedPromo='';discount=0;msg.textContent='Enter a promo code.';msg.className='promoMsg error';refreshTotals();return}btn.disabled=true;btn.textContent='Checking…';msg.textContent='';try{const {data,error}=await window.sgSupabase.rpc('validate_promo_code',{p_code:code,p_subtotal:subtotal});if(error)throw error;if(!data?.valid){appliedPromo='';discount=0;msg.textContent=data?.message||'Promo code is not valid.';msg.className='promoMsg error'}else{appliedPromo=data.code||code;discount=Number(data.discount_inr||0);input.value=appliedPromo;msg.textContent=`${data.message||'Promo code applied'} · You save ${money(discount)}`;msg.className='promoMsg success'}refreshTotals()}catch(e){appliedPromo='';discount=0;msg.textContent='Could not check this promo code. Please try again.';msg.className='promoMsg error';refreshTotals()}finally{btn.disabled=false;btn.textContent='Apply'}}
async function init(){products=await window.SGStore.loadProducts();cart=readCart();const validCart=cart.filter(i=>resolve(i));if(validCart.length!==cart.length){cart=validCart;localStorage.setItem('sg_cart',JSON.stringify(cart))}const lines=cart.map(resolve).filter(Boolean);if(!lines.length){$('#checkoutMain').innerHTML='<section class="checkoutCard orderSuccess"><h1>Your bag is empty</h1><p>Old or unavailable items were removed from your bag. Add a current product before checkout.</p><a class="primary" href="index.html#shop">Return to Shop</a></section>';return}$('#checkoutItems').innerHTML=lines.map(r=>`<div class="checkoutLine"><img src="${r.p.image||''}" alt=""><div><b>${r.p.name}</b>${r.v?.label?`<small style="display:block">${r.v.label}</small>`:''}<small>Qty ${r.qty}</small></div><b>${money(r.price*r.qty)}</b></div>`).join('');subtotal=lines.reduce((a,r)=>a+r.price*r.qty,0);refreshTotals();$('#applyPromo').onclick=applyPromo;$('#promoCode').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();applyPromo()}})}
$('#checkoutForm').onsubmit=async e=>{e.preventDefault();const b=$('#placeOrder'),m=$('#checkoutMsg');b.disabled=true;b.textContent='Placing order…';m.textContent='';const validCart=readCart().filter(i=>resolve(i));if(!validCart.length){m.textContent='Your bag has no valid products. Please add the product again.';m.style.color='#a10f28';b.disabled=false;b.textContent='Place Order';return}const payload={customer:{name:$('#cName').value.trim(),phone:$('#cPhone').value.trim(),email:$('#cEmail').value.trim()},address:{line1:$('#cLine1').value.trim(),line2:$('#cLine2').value.trim(),city:$('#cCity').value.trim(),state:$('#cState').value.trim(),pincode:$('#cPincode').value.trim()},items:validCart.map(i=>({product_id:i.productId||i.product_id,variant_id:i.variantId||i.variant_id||null,quantity:Number(i.qty||i.quantity||1)})),promo_code:appliedPromo};try{const r=await fetch(`${window.SG_SUPABASE_URL}/functions/v1/create-order`,{method:'POST',headers:{'Content-Type':'application/json','apikey':window.SG_SUPABASE_KEY,'Authorization':`Bearer ${window.SG_SUPABASE_KEY}`},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw new Error(data.error||'Could not place order');localStorage.setItem('sg_cart','[]');$('#checkoutMain').innerHTML=`<section class="checkoutCard orderSuccess" style="grid-column:1/-1"><p class="kicker burgundy">ORDER RECEIVED</p><h1>Thank you.</h1><p>Your order request has been recorded successfully.</p><p class="orderNumber">${data.order_number}</p>${Number(data.discount_inr||0)>0?`<p>Promotional discount: <b>− ${money(data.discount_inr)}</b></p>`:''}<p>Total: <b>${money(data.total_inr)}</b></p><p>Payment is pending. Shree Gauri will confirm payment and shipping details with you.</p><a class="primary" href="index.html">Continue Shopping</a></section>`}catch(err){m.textContent=err.message;m.style.color='#a10f28';b.disabled=false;b.textContent='Place Order'}};
init();
