'use client';
import {FormEvent,useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';
import {Heart,ShoppingBag,UserRound} from 'lucide-react';

export default function CustomerLogin(){
 const[mode,setMode]=useState<'login'|'signup'>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[message,setMessage]=useState(''),[user,setUser]=useState<any>(null);
 useEffect(()=>{supabase.auth.getUser().then(({data})=>setUser(data.user));const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user||null));return()=>subscription.unsubscribe()},[]);
 async function submit(e:FormEvent){e.preventDefault();setMessage('Please wait...');if(mode==='login'){const{error}=await supabase.auth.signInWithPassword({email,password});setMessage(error?.message||'Welcome back.')}else{const{error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name}}});setMessage(error?.message||'Account created. Please check your email if verification is required.')}}
 if(user)return <main className="customer-auth"><section className="account-card"><a href="/">← Return to Shree Gauri</a><div className="account-icon"><UserRound/></div><small>MY ACCOUNT</small><h1>Welcome to Shree Gauri</h1><p>{user.user_metadata?.full_name||user.email}</p><div className="account-links"><a href="/"><ShoppingBag/>Continue Shopping</a><a href="/"><Heart/>View Wishlist</a></div><button onClick={()=>supabase.auth.signOut()}>LOG OUT</button></section></main>;
 return <main className="customer-auth"><section className="login-panel"><div className="login-art"><span>श्रीं</span><h2>Welcome to<br/>Shree Gauri</h2><p>Save your favourites, view your orders and enjoy a more personal shopping experience.</p></div><form onSubmit={submit}><a href="/">← Return to store</a><small>YOUR SHREE GAURI ACCOUNT</small><h1>{mode==='login'?'Welcome Back':'Create Your Account'}</h1>{mode==='signup'&&<label>Full Name<input value={name} onChange={e=>setName(e.target.value)} required/></label>}<label>Email Address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" minLength={6} value={password} onChange={e=>setPassword(e.target.value)} required/></label>{message&&<p className="auth-message">{message}</p>}<button>{mode==='login'?'LOGIN':'CREATE ACCOUNT'}</button><p>{mode==='login'?'New to Shree Gauri?':'Already have an account?'} <button type="button" className="text-button" onClick={()=>{setMode(mode==='login'?'signup':'login');setMessage('')}}>{mode==='login'?'Create account':'Login'}</button></p></form></section></main>
}
